### ISSUE TITLE
[Bug]: No Man's Sky Crashes when changing graphics settings & missing input icons

### ISSUE THREAD

**Issue by JosSamLoh** [Supreeeme/xrizer#178]
### Operating System

Arch

### OpenXR Runtime

WiVRn

### Describe the issue.

# Graphics Settings Crash
<img width="724" height="616" alt="Image" src="https://github.com/user-attachments/assets/35691874-a237-487c-9801-5b26408f2fd9" />

No Man's Sky works great other than when I change some graphics settings, which causes it to crash in specific scenarios.

# Missing input icons
<img width="528" height="169" alt="Image" src="https://github.com/user-attachments/assets/a9bc5030-4638-490a-bb25-2e844c38560e" />

Some icons, as shown above, instead of showing their mapped button show this (⚠️) icon instead. Though most do show up correctly. This is using an unmodified version of xrizer.

However, it seems when accidentally using a modified xriser, specifically [Zero's fork](https://github.com/Mr-Zero88/xrizer/tree/main), **all** input icons get turned into the warning icon. Which lead me to believe that this is an xriser issue.

[xrizer.txt](https://github.com/user-attachments/files/22028148/xrizer.txt)

### Steps to reproduce

1. Launch NMS in VR
2. Stay in Main Menu
3. Go to Settings
4. Change any setting besides anti-aliasing > Doesn't crash

And

1. Launch NMS in VR
2. Enter the game
3. Go to Settings
4. Change any settings > Crash

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

**Comment by Supreeeme** [comment]
The input icons issue is already tracked at #162.

**Comment by Supreeeme** [comment]
Likely fixed with #192

**Comment by JosSamLoh** [comment]
> Likely fixed with [#192](https://github.com/Supreeeme/xrizer/pull/192)

Unfortunately seems to crash still:
[xrizer.txt](https://github.com/user-attachments/files/22279517/xrizer.txt)

**Comment by JosSamLoh** [comment]
> > Likely fixed with [#192](https://github.com/Supreeeme/xrizer/pull/192)
> 
> Unfortunately seems to crash still: [xrizer.txt](https://github.com/user-attachments/files/22279517/xrizer.txt)

Seems to work with the latest changes from Zero, no more crashing when changing options in main menu or in game.

**Comment by Mr-Zero88** [comment]
It is now fixed by https://github.com/Supreeeme/xrizer/pull/192
