### ISSUE TITLE
Resonite doesn't show anything in the headset

### ISSUE THREAD

**Issue by OrionMoonclaw** [Supreeeme/xrizer#36]
With 50565f490e08d2cec58cdbb0e821f18ea0bd7ce1 reverted Resonite still doesn't render anything in the headset, even though it can be seen tracking the head pose in the desktop window.

With RUST_LOG=trace: [xrizer.txt.gz](https://github.com/user-attachments/files/18510261/xrizer.txt.gz)

It appears 680833891ec7b849d06879063578fc7b7d2dd982 is implicated here, reverting that and applying the following diff makes everything work again: (image_acquired check added because of a panic there)
```diff
diff --git a/src/compositor.rs b/src/compositor.rs
index 8d1d4a3..3706599 100644
--- a/src/compositor.rs
+++ b/src/compositor.rs
@@ -99,7 +99,9 @@ impl Compositor {
             AnyTempBackendData: From<TempBackendData<G>>,
         {
             let b_texture = G::get_texture(texture);
-            let info = backend.swapchain_info_for_texture(b_texture, bounds, texture.eColorSpace);
+            let mut info = backend.swapchain_info_for_texture(b_texture, bounds, texture.eColorSpace);
+            info.width = info.width.max(1);
+            info.height = info.height.max(1);
             TempBackendData {
                 backend,
                 swapchain_create_info: info,
@@ -862,8 +864,10 @@ impl<G: GraphicsBackend> FrameController<G> {
         // Both eyes submitted: show our images
 
         trace!("releasing image");
-        self.swapchain_data.swapchain.release_image().unwrap();
-        self.image_acquired = false;
+        if self.image_acquired {
+            self.swapchain_data.swapchain.release_image().unwrap();
+            self.image_acquired = false;
+        }
 
         let mut proj_layer_views = Vec::new();
         if self.should_render {
```

**Comment by Supreeeme** [comment]
The provided log crashes with the action set issue that was fixed. Could you get a log with `RUST_LOG=xrizer::compositor,xrizer::graphics_backends`

**Comment by OrionMoonclaw** [comment]
Seems like it works fine now

**Comment by Mhowser** [comment]
I'm still not able to see the game in my headset.

Using Pico 4 with Wivrn master branch, latest Xrizer built with Envision, Arch Linux

Hardware is AMD Ryzen 9 7950X3D, 7600XT GPU

[xrizer.txt](https://github.com/user-attachments/files/18924621/xrizer.txt)

[Player.log](https://github.com/user-attachments/files/18924622/Player.log)

[RACCOON - 2025.2.21.98 - 2025-02-22 09_58_31.log](https://github.com/user-attachments/files/18924637/RACCOON.-.2025.2.21.98.-.2025-02-22.09_58_31.log)

Here is a successful launch with open composite:

[RACCOON - 2025.2.21.98 - 2025-02-22 10_09_31.log](https://github.com/user-attachments/files/18924662/RACCOON.-.2025.2.21.98.-.2025-02-22.10_09_31.log)

[Player.log](https://github.com/user-attachments/files/18924663/Player.log)

[opencomposite.log](https://github.com/user-attachments/files/18924664/opencomposite.log)

**Comment by phil-flip** [comment]
Seems to have similar issues with Resonite on my end. WLX loads fine, and headset tracking works. just not controllers and no display.

**Comment by Mhowser** [comment]
A month later and this bug is still present. Here is my xrizer log made with `RUST_LOG=trace` 

[xrizer.tar.gz](https://github.com/user-attachments/files/19357770/xrizer.tar.gz)

Can we reopen this issue please?

**Comment by phil-flip** [comment]
@Mhowser I have been told to make a new issue. I need to get the logs myself too.

**Comment by Supreeeme** [comment]
Please open a new issue.
